spring:
  sql:
    init:
      data-locations:
        - classpath:data.sql
  datasource:
    url: jdbc:h2:mem:testing
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2console
      enabled: true
      settings:
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
